// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"cn.meow/meowtv/internal/auth"
	"cn.meow/meowtv/internal/cache"
	"cn.meow/meowtv/internal/config"
	"cn.meow/meowtv/internal/handler"
	"cn.meow/meowtv/internal/handler/middleware"
	"cn.meow/meowtv/internal/repository"
	"cn.meow/meowtv/internal/router"
	"cn.meow/meowtv/internal/service"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeApp 是 wire injector 入口。
// cfg 和 db 参数由 main.go 提前创建并传入（因为需要先做迁移和日志初始化）。
// wire 将根据 Provider Set 自动生成此函数的实现到 wire_gen.go。
func InitializeApp(cfg *config.Config, db *gorm.DB) (*App, error) {
	cacheConfig := ProvideCacheConfig(cfg)
	cacheProvider, err := cache.NewCacheProvider(cacheConfig)
	if err != nil {
		return nil, err
	}
	authConfig := ProvideAuthConfig(cfg)
	jwtManager := auth.NewJWTManager(authConfig)
	cacheCache := ProvideCache(cacheProvider)
	deviceSessionTTL := ProvideDeviceSessionTTL(authConfig)
	blacklistManager := auth.NewBlacklistManager(cacheCache, deviceSessionTTL)
	authMiddleware := middleware.NewAuthProviders(jwtManager, blacklistManager)
	sysConfigRepository := repository.NewSysConfigRepository(db)
	sysConfigService := service.NewSysConfigService(sysConfigRepository, cacheCache)
	userGroupRepository := repository.NewUserGroupRepository(db)
	userRepository := repository.NewUserRepository(db)
	userGroupService := service.NewUserGroupService(userGroupRepository, userRepository, cacheCache)
	resourceService := service.NewResourceService(sysConfigService, userGroupService, cacheCache)
	doubanClient := service.NewDoubanClient(sysConfigService, cacheCache)
	doubanImageService := service.NewDoubanImageService(doubanClient, sysConfigService, cacheCache)
	doubanRankRepository := repository.NewDoubanRankRepository(db)
	doubanRankService := service.NewDoubanRankService(doubanRankRepository, doubanClient, sysConfigService, cacheCache)
	resourceImageService := service.NewResourceImageService(sysConfigService, cacheCache)
	downloadRepository := repository.NewDownloadRepository(db)
	downloadService := service.NewDownloadService(downloadRepository, sysConfigService, cacheCache)
	streamService := service.NewStreamService(sysConfigService, downloadService)
	qrCodeManager := auth.NewQRCodeManager(cacheCache)
	authService := service.NewAuthService(cfg, userRepository, jwtManager, blacklistManager, qrCodeManager, cacheCache)
	authHandler := handler.NewAuthHandler(authService)
	userService := service.NewUserService(userRepository, blacklistManager, userGroupService)
	userHandler := handler.NewUserHandler(userService)
	adminHandler := handler.NewAdminHandler(userService)
	adminConfigHandler := handler.NewAdminConfigHandler(sysConfigService)
	adminGroupHandler := handler.NewAdminGroupHandler(userGroupService)
	localVideoRepository := repository.NewLocalVideoRepository(db)
	localDataDir := ProvideDemoLocalDataDir(cfg)
	localDataService := service.NewLocalDataService(localVideoRepository, downloadRepository, sysConfigRepository, localDataDir)
	doubanService := service.NewDoubanService(doubanClient, doubanRankService, localDataService)
	doubanHandler := handler.NewDoubanHandler(doubanService, doubanImageService)
	searchService := service.NewSearchService(sysConfigService, userGroupService, cacheCache, localVideoRepository, localDataService)
	resourceHandler := handler.NewResourceHandler(resourceService, searchService, resourceImageService, sysConfigService)
	searchHistoryRepository := repository.NewSearchHistoryRepository(db)
	searchHistoryService := service.NewSearchHistoryService(searchHistoryRepository)
	playHistoryRepository := repository.NewPlayHistoryRepository(db)
	playHistoryService := service.NewPlayHistoryService(playHistoryRepository)
	favoriteRepository := repository.NewFavoriteRepository(db)
	favoriteService := service.NewFavoriteService(favoriteRepository, cacheCache)
	userDataHandler := handler.NewUserDataHandler(searchHistoryService, playHistoryService, favoriteService, streamService)
	downloadHandler := handler.NewDownloadHandler(downloadService)
	streamHandler := handler.NewStreamHandler(streamService)
	tempTokenHandler := handler.NewTempTokenHandler(cacheCache)
	handlers := &router.Handlers{
		Auth:        authHandler,
		User:        userHandler,
		Admin:       adminHandler,
		AdminConfig: adminConfigHandler,
		AdminGroup:  adminGroupHandler,
		Douban:      doubanHandler,
		Resource:    resourceHandler,
		UserData:    userDataHandler,
		Download:    downloadHandler,
		Stream:      streamHandler,
		TempToken:   tempTokenHandler,
	}
	app := &App{
		Config:               cfg,
		CacheProvider:        cacheProvider,
		JWTManager:           jwtManager,
		BlacklistManager:     blacklistManager,
		AuthMiddleware:       authMiddleware,
		SysConfigService:     sysConfigService,
		ResourceService:      resourceService,
		DoubanImageService:   doubanImageService,
		DoubanRankService:    doubanRankService,
		ResourceImageService: resourceImageService,
		DownloadService:      downloadService,
		StreamService:        streamService,
		LocalDataService:     localDataService,
		Handlers:             handlers,
	}
	return app, nil
}

// wire.go:

// ConfigSet provides configuration sub-config extraction providers.
// *Config itself is provided as an injector argument (loaded in main.go before wire).
var ConfigSet = wire.NewSet(
	ProvideAuthConfig,
	ProvideDBConfig,
	ProvideCacheConfig,
	ProvideAppConfig,
)

// CacheSet provides cache-related dependencies.
var CacheSet = wire.NewSet(cache.NewCacheProvider, ProvideCache)

// DBSet is intentionally empty.
// *gorm.DB is created in main.go before wire injection (for migrations),
// so it is provided as an injector argument instead of a provider.
var DBSet = wire.NewSet()

// AuthSet provides auth-related dependencies.
var AuthSet = wire.NewSet(auth.NewJWTManager, auth.NewBlacklistManager, auth.NewQRCodeManager)

// RepositorySet provides repository layer dependencies.
var RepositorySet = wire.NewSet(repository.NewUserRepository, repository.NewSysConfigRepository, repository.NewUserGroupRepository, repository.NewSearchHistoryRepository, repository.NewPlayHistoryRepository, repository.NewFavoriteRepository, repository.NewDownloadRepository, repository.NewDoubanRankRepository)

// ServiceSet provides service layer dependencies.
var ServiceSet = wire.NewSet(service.NewAuthService, service.NewUserService, service.NewSysConfigService, service.NewDoubanClient, service.NewDoubanService, service.NewDoubanImageService, service.NewDoubanRankService, service.NewResourceService, service.NewResourceImageService, service.NewSearchService, service.NewSearchHistoryService, service.NewPlayHistoryService, service.NewFavoriteService, service.NewDownloadService, service.NewUserGroupService, service.NewStreamService)

// HandlerSet provides handler layer dependencies.
var HandlerSet = wire.NewSet(handler.NewAuthHandler, handler.NewUserHandler, handler.NewAdminHandler, handler.NewAdminConfigHandler, handler.NewAdminGroupHandler, handler.NewDoubanHandler, handler.NewResourceHandler, handler.NewUserDataHandler, handler.NewDownloadHandler, handler.NewStreamHandler)

// SuperSet contains all provider sets.
var SuperSet = wire.NewSet(
	ConfigSet,
	CacheSet,
	DBSet,
	AuthSet,
	RepositorySet,
	ServiceSet,
	HandlerSet,
)
